### ISSUE TITLE
--count doesn't work with ambiegen 

### ISSUE THREAD

**Issue by neelofarhassan** [christianbirchler-org/sdc-scissor#104]
# Steps to reproduce the bug
sdc-scissor generate-tests --count 200 --no-keep -d PATH_TO_DESTINATION_DIRECTORY -t ambiegen

# Resulting and expected behavior
The number of tests generated is always less than 10. However, this parameter works fine with the default test generator.

**Comment by ChristianBirchler** [comment]
Hi @neelofarhassan , thanks a lot for this report. I just figured out that the `ambiegen` tool is not compatible anymore with the recent dependencies of SDC-Scissor. I suggest using the original `ambiegen` implementation at https://github.com/dgumenyuk/tool-competition-av

In general, if you want to experiment with test generators, I suggest using the original implementations since SDC-Scissor updates its dependencies and sometimes the generators are not compatible anymore. Furthermore, SDC-Scissor's focus is not on test generation itself, but on implementing regression techniques. However, SDC-Scissor is a good tool to run the tests with the BeamNG simulator and provides APIs to extend the tool by new regression testing approaches.

I hope it helps you.

Best,
Christian

**Comment by neelofarhassan** [comment]
Thank you, Christian.

Best Regards,
Neelofar

**Comment by swat-lab-optimization** [comment]
Hi @neelofarhassan ! This issue was resolved, it should work now.

**Comment by neelofarhassan** [comment]
Thank you, Christian.

Best Regards,
Neelofar
